// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import DarkModeToggleController from "./dark_mode_toggle_controller"
application.register("dark-mode-toggle", DarkModeToggleController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ExpandableFabController from "./expandable_fab_controller"
application.register("expandable-fab", ExpandableFabController)

import GoogleFitController from "./google_fit_controller"
application.register("google-fit", GoogleFitController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
